#!/bin/bash

# MultiOS Enterprise Deployment Tools Setup Script
# This script sets up the entire enterprise deployment environment

set -e

echo "======================================"
echo "MultiOS Enterprise Deployment Tools Setup"
echo "======================================"

# Check if running as root
if [[ $EUID -eq 0 ]]; then
   echo "This script should not be run as root for security reasons." 
   echo "Please run as a regular user with sudo privileges."
   exit 1
fi

# Install system dependencies
echo "Installing system dependencies..."
sudo apt update
sudo apt install -y \
    python3 \
    python3-pip \
    python3-dev \
    python3-yaml \
    build-essential \
    git \
    curl \
    wget \
    jq \
    isc-dhcp-server \
    tftpd-hpa \
    syslinux \
    xinetd \
    nginx \
    postgresql \
    postgresql-contrib \
    ldap-utils \
    slapd \
    libldap-common \
    ldap3 \
    psutils \
    htop \
    tree \
    vim \
    net-tools \
    dnsutils \
    nmap

# Install Python packages
echo "Installing Python packages..."
pip3 install --user \
    psutil \
    jinja2 \
    pyyaml \
    requests \
    ldap3 \
    psutil \
    colorama \
    tabulate

# Create system user for MultiOS
echo "Creating MultiOS system user..."
sudo useradd -r -s /bin/false -d /var/lib/multios-enterprise multios 2>/dev/null || true
sudo mkdir -p /var/lib/multios-enterprise
sudo mkdir -p /var/log/multios-enterprise
sudo mkdir -p /var/cache/multios-enterprise
sudo mkdir -p /etc/multios-enterprise

# Set ownership and permissions
sudo chown -R multios:multios /var/lib/multios-enterprise
sudo chown -R multios:multios /var/log/multios-enterprise
sudo chown -R multios:multios /var/cache/multios-enterprise
sudo chown -R multios:multios /etc/multios-enterprise

sudo chmod 755 /var/lib/multios-enterprise
sudo chmod 755 /var/log/multios-enterprise
sudo chmod 755 /var/cache/multios-enterprise
sudo chmod 755 /etc/multios-enterprise

# Copy enterprise tools to system location
echo "Installing MultiOS Enterprise tools..."
INSTALL_DIR="/opt/multios-enterprise"
sudo mkdir -p "$INSTALL_DIR"
sudo cp -r /workspace/deployment/enterprise_tools/* "$INSTALL_DIR/"
sudo chmod +x "$INSTALL_DIR"/scripts/*.sh 2>/dev/null || true

# Create symlinks for easy access
sudo ln -sf "$INSTALL_DIR/scripts/multios-enterprise" /usr/local/bin/multios-enterprise
sudo ln -sf "$INSTALL_DIR/scripts/deploy-lab" /usr/local/bin/deploy-lab
sudo ln -sf "$INSTALL_DIR/scripts/monitor-systems" /usr/local/bin/monitor-systems

# Create systemd service files
echo "Creating systemd services..."

# Main manager service
sudo tee /etc/systemd/system/multios-enterprise-manager.service > /dev/null <<EOF
[Unit]
Description=MultiOS Enterprise Deployment Manager
After=network.target

[Service]
Type=simple
User=multios
Group=multios
WorkingDirectory=/opt/multios-enterprise
ExecStart=/usr/bin/python3 /opt/multios-enterprise/core/manager.py
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

# PXE server service
sudo tee /etc/systemd/system/multios-enterprise-pxe.service > /dev/null <<EOF
[Unit]
Description=MultiOS Enterprise PXE Server
After=network.target isc-dhcp-server.service xinetd.service

[Service]
Type=simple
User=root
WorkingDirectory=/var/lib/tftpboot
ExecStart=/usr/bin/python3 /opt/multios-enterprise/pxe_installer/pxe_server.py
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

# Update server service
sudo tee /etc/systemd/system/multios-enterprise-update.service > /dev/null <<EOF
[Unit]
Description=MultiOS Enterprise Update Server
After=network.target

[Service]
Type=simple
User=multios
WorkingDirectory=/opt/multios-enterprise
ExecStart=/usr/bin/python3 /opt/multios-enterprise/update_distribution/update_server.py
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

# System monitoring service
sudo tee /etc/systemd/system/multios-enterprise-monitor.service > /dev/null <<EOF
[Unit]
Description=MultiOS Enterprise System Monitor
After=network.target

[Service]
Type=simple
User=multios
WorkingDirectory=/opt/multios-enterprise
ExecStart=/usr/bin/python3 /opt/multios-enterprise/system_monitoring/monitor.py
Restart=always
RestartSec=30

[Install]
WantedBy=multi-user.target
EOF

# Reload systemd
sudo systemctl daemon-reload

# Enable services
sudo systemctl enable multios-enterprise-manager
sudo systemctl enable multios-enterprise-pxe
sudo systemctl enable multios-enterprise-update
sudo systemctl enable multios-enterprise-monitor

# Configure DHCP server for PXE
echo "Configuring DHCP server..."
sudo tee /etc/dhcp/dhcpd.conf > /dev/null <<EOF
# MultiOS Enterprise DHCP Configuration
# Generated by setup script

default-lease-time 7200;
max-lease-time 43200;
authoritative;

# PXE boot configuration
allow booting;
allow bootp;

# Network configuration
option domain-name "multios.local";
option domain-name-servers 8.8.8.8 8.8.4.4;
option routers 192.168.1.1;

# PXE server settings
next-server 192.168.1.1;
filename "pxelinux.0";

# Default subnet for MultiOS network
subnet 192.168.1.0 netmask 255.255.255.0 {
    range 192.168.1.100 192.168.1.200;
    option broadcast-address 192.168.1.255;
    option routers 192.168.1.1;
}

# Add static reservations as needed:
# host desktop-001 {
#     hardware ethernet aa:bb:cc:dd:ee:ff;
#     fixed-address 192.168.1.10;
#     filename "multios/multios-desktop.bin";
# }
EOF

# Configure TFTP server
echo "Configuring TFTP server..."
sudo tee /etc/xinetd.d/tftp > /dev/null <<EOF
service tftp
{
    socket_type = dgram
    protocol = udp
    wait = yes
    user = root
    server = /usr/sbin/in.tftpd
    server_args = -s /var/lib/tftpboot -v
    disable = no
    per_source = 11
    cps = 100 2
    flags = IPv4
}
EOF

# Create PXE directories
sudo mkdir -p /var/lib/tftpboot/{pxelinux.cfg,images,kernels,multios}

# Configure Nginx for update server
echo "Configuring Nginx..."
sudo tee /etc/nginx/sites-available/multios-enterprise > /dev/null <<EOF
server {
    listen 8080;
    server_name _;
    
    location / {
        root /var/lib/multios-enterprise/updates;
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
    }
    
    location /api/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }
}
EOF

sudo ln -sf /etc/nginx/sites-available/multios-enterprise /etc/nginx/sites-enabled/
sudo rm -f /etc/nginx/sites-enabled/default

# Test nginx configuration
sudo nginx -t

# Create default configuration files
echo "Creating default configuration files..."

# Main configuration
sudo tee /etc/multios-enterprise/enterprise_config.yaml > /dev/null <<EOF
# MultiOS Enterprise Deployment System Configuration
# Generated by setup script

sites:
  main_campus:
    site_id: "CAMPUS001"
    name: "Main Campus"
    address: "123 University Ave, Campus City, State 12345"
    network_range: "192.168.1.0/24"
    dhcp_range: "192.168.1.100-192.168.1.200"
    dns_servers: ["8.8.8.8", "8.8.4.4"]
    ntp_servers: ["pool.ntp.org"]
    timezone: "America/New_York"
    backup_enabled: true
    monitoring_enabled: true

deployment:
  max_concurrent_deployments: 100
  default_timeout: 3600
  retry_attempts: 3
  backup_enabled: true

monitoring:
  interval: 300
  health_check_enabled: true
  alert_thresholds:
    cpu_usage: 80
    memory_usage: 85
    disk_usage: 90

security:
  ldap_enabled: false
  ssl_enabled: true
  audit_logging: true

logging:
  level: "INFO"
  file: "/var/log/multios-enterprise/multios-enterprise.log"
EOF

# PXE configuration
sudo tee /etc/multios-enterprise/pxe.yaml > /dev/null <<EOF
# MultiOS Enterprise PXE Server Configuration
# Generated by setup script

dhcp_enabled: true
dhcp_range: "192.168.1.100-192.168.1.200"
dhcp_lease_time: "7200"
boot_filename: "pxelinux.0"
next_server: "192.168.1.1"
boot_images: {}
install_profiles: {}
EOF

# Monitoring configuration
sudo tee /etc/multios-enterprise/monitoring.yaml > /dev/null <<EOF
# MultiOS Enterprise Monitoring Configuration
# Generated by setup script

monitoring:
  interval: 300
  timeout: 30
  max_workers: 50

thresholds:
  cpu_usage: 80.0
  memory_usage: 85.0
  disk_usage: 90.0
  network_latency: 100.0
  process_count: 1000

health_checks:
  enabled: true
  check_interval: 600
  services_to_check: ['ssh', 'http', 'https', 'dns']

alerts:
  enabled: true
  email_notifications:
    enabled: false
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""
    recipients: []
  slack_notifications:
    enabled: false
    webhook_url: ""
    channel: "#alerts"

retention:
  health_check_history_days: 30
  performance_data_hours: 168
EOF

# Initialize database
echo "Initializing database..."
sudo -u postgres psql <<EOF
CREATE DATABASE multios_enterprise;
CREATE USER multios_user WITH ENCRYPTED PASSWORD 'multios_password';
GRANT ALL PRIVILEGES ON DATABASE multios_enterprise TO multios_user;
\q
EOF

# Create logrotate configuration
echo "Creating logrotate configuration..."
sudo tee /etc/logrotate.d/multios-enterprise > /dev/null <<EOF
/var/log/multios-enterprise/*.log {
    daily
    missingok
    rotate 52
    compress
    delaycompress
    notifempty
    create 644 multios multios
    postrotate
        systemctl reload multios-enterprise-manager > /dev/null 2>&1 || true
        systemctl reload multios-enterprise-monitor > /dev/null 2>&1 || true
    endscript
}
EOF

# Create backup script
sudo tee /opt/multios-enterprise/scripts/backup.sh > /dev/null <<'EOF'
#!/bin/bash

# MultiOS Enterprise Backup Script

BACKUP_DIR="/var/backups/multios-enterprise"
DATE=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="$BACKUP_DIR/multios-backup-$DATE.tar.gz"

echo "Creating MultiOS Enterprise backup..."

# Create backup directory
mkdir -p "$BACKUP_DIR"

# Backup configuration and data
tar -czf "$BACKUP_FILE" \
    /etc/multios-enterprise \
    /var/lib/multios-enterprise \
    /var/log/multios-enterprise \
    --exclude="/var/log/multios-enterprise/*.log" \
    --exclude="*.tmp"

# Compress old logs
find /var/log/multios-enterprise -name "*.log" -mtime +7 -exec gzip {} \;

# Clean old backups (keep last 30 days)
find "$BACKUP_DIR" -name "multios-backup-*.tar.gz" -mtime +30 -delete

echo "Backup completed: $BACKUP_FILE"
EOF

sudo chmod +x /opt/multios-enterprise/scripts/backup.sh

# Create cron job for backups
(crontab -l 2>/dev/null; echo "0 2 * * * /opt/multios-enterprise/scripts/backup.sh") | crontab -

# Create status check script
sudo tee /opt/multios-enterprise/scripts/status.sh > /dev/null <<'EOF'
#!/bin/bash

# MultiOS Enterprise Status Check Script

echo "========================================="
echo "MultiOS Enterprise System Status"
echo "========================================="

# Check services
echo "Services Status:"
for service in multios-enterprise-manager multios-enterprise-pxe multios-enterprise-update multios-enterprise-monitor; do
    if systemctl is-active --quiet $service; then
        echo "  ✓ $service: Running"
    else
        echo "  ✗ $service: Stopped"
    fi
done

# Check disk space
echo ""
echo "Disk Space:"
df -h / | tail -1 | awk '{print "  Root: " $3 " used of " $2 " (" $5 " used)"}'
df -h /var/lib | tail -1 | awk '{print "  Data: " $3 " used of " $2 " (" $5 " used)"}'

# Check network services
echo ""
echo "Network Services:"
if systemctl is-active --quiet isc-dhcp-server; then
    echo "  ✓ DHCP Server: Running"
else
    echo "  ✗ DHCP Server: Stopped"
fi

if systemctl is-active --quiet xinetd; then
    echo "  ✓ TFTP Server: Running"
else
    echo "  ✗ TFTP Server: Stopped"
fi

if systemctl is-active --quiet nginx; then
    echo "  ✓ Web Server: Running"
else
    echo "  ✗ Web Server: Stopped"
fi

# Check log files
echo ""
echo "Recent Log Entries:"
if [ -f /var/log/multios-enterprise/multios-enterprise.log ]; then
    echo "  Main log (last 5 lines):"
    tail -5 /var/log/multios-enterprise/multios-enterprise.log | sed 's/^/    /'
else
    echo "  No main log file found"
fi

echo ""
echo "========================================="
EOF

sudo chmod +x /opt/multios-enterprise/scripts/status.sh

# Create uninstall script
sudo tee /opt/multios-enterprise/scripts/uninstall.sh > /dev/null <<'EOF'
#!/bin/bash

# MultiOS Enterprise Uninstall Script

echo "Warning: This will completely remove MultiOS Enterprise Deployment Tools"
read -p "Are you sure you want to continue? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
    echo "Uninstall cancelled"
    exit 1
fi

echo "Stopping services..."
sudo systemctl stop multios-enterprise-manager
sudo systemctl stop multios-enterprise-pxe
sudo systemctl stop multios-enterprise-update
sudo systemctl stop multios-enterprise-monitor

echo "Disabling services..."
sudo systemctl disable multios-enterprise-manager
sudo systemctl disable multios-enterprise-pxe
sudo systemctl disable multios-enterprise-update
sudo systemctl disable multios-enterprise-monitor

echo "Removing systemd service files..."
sudo rm -f /etc/systemd/system/multios-enterprise-*.service
sudo systemctl daemon-reload

echo "Removing application files..."
sudo rm -rf /opt/multios-enterprise
sudo rm -f /usr/local/bin/multios-enterprise
sudo rm -f /usr/local/bin/deploy-lab
sudo rm -f /usr/local/bin/monitor-systems

echo "Removing configuration files..."
sudo rm -rf /etc/multios-enterprise
sudo rm -rf /var/lib/multios-enterprise
sudo rm -rf /var/log/multios-enterprise
sudo rm -rf /var/cache/multios-enterprise

echo "Removing database..."
sudo -u postgres psql <<EOF
DROP DATABASE IF EXISTS multios_enterprise;
DROP USER IF EXISTS multios_user;
\q
EOF

echo "Removing logrotate configuration..."
sudo rm -f /etc/logrotate.d/multios-enterprise

echo "Uninstall completed"
EOF

sudo chmod +x /opt/multios-enterprise/scripts/uninstall.sh

# Set final permissions
sudo chown -R multios:multios /opt/multios-enterprise
sudo find /opt/multios-enterprise -type d -exec chmod 755 {} \;
sudo find /opt/multios-enterprise -type f -exec chmod 644 {} \;
sudo chmod +x /opt/multios-enterprise/scripts/*.sh

echo ""
echo "======================================"
echo "Setup Complete!"
echo "======================================"
echo ""
echo "MultiOS Enterprise Deployment Tools has been installed successfully."
echo ""
echo "Next steps:"
echo "1. Review and customize configuration files in /etc/multios-enterprise/"
echo "2. Start the services: sudo systemctl start multios-enterprise-manager"
echo "3. Check system status: /opt/multios-enterprise/scripts/status.sh"
echo "4. Access documentation: /opt/multios-enterprise/README.md"
echo ""
echo "Services installed:"
echo "  - multios-enterprise-manager (Main deployment manager)"
echo "  - multios-enterprise-pxe (PXE boot server)"
echo "  - multios-enterprise-update (Update distribution)"
echo "  - multios-enterprise-monitor (System monitoring)"
echo ""
echo "Management scripts available:"
echo "  - multios-enterprise (Main CLI tool)"
echo "  - deploy-lab (Deploy lab environments)"
echo "  - monitor-systems (System monitoring)"
echo "  - /opt/multios-enterprise/scripts/status.sh (System status)"
echo "  - /opt/multios-enterprise/scripts/backup.sh (Backup utility)"
echo "  - /opt/multios-enterprise/scripts/uninstall.sh (Uninstall)"
echo ""
echo "Log files location: /var/log/multios-enterprise/"
echo "Configuration location: /etc/multios-enterprise/"
echo "Data location: /var/lib/multios-enterprise/"
echo ""
echo "For detailed usage instructions, see: /opt/multios-enterprise/README.md"
