name: Release Pipeline

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.2.3)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  DOCKER_BUILDKIT: 1

jobs:
  # Build release artifacts for all architectures
  build-release:
    name: Build Release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-none
            os: ubuntu-latest
            cross: false
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            cross: false
          - target: aarch64-unknown-none
            os: ubuntu-latest
            cross: true
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
          - target: riscv64gc-unknown-none-elf
            os: ubuntu-latest
            cross: true
          - target: riscv64gc-unknown-linux-musl
            os: ubuntu-latest
            cross: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        if: matrix.cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build release binary
        run: |
          if [ "${{ matrix.cross }}" = "true" ]; then
            cross build --target ${{ matrix.target }} --release --all-features
          else
            cargo build --target ${{ matrix.target }} --release --all-features
          fi

      - name: Strip binary
        run: |
          if [ "${{ matrix.target }}" != "x86_64-unknown-none" ]; then
            strip target/${{ matrix.target }}/release/multios
          fi

      - name: Create release package
        run: |
          mkdir -p release/${{ matrix.target }}
          cp target/${{ matrix.target }}/release/multios release/${{ matrix.target }}/
          cp README.md release/${{ matrix.target }}/
          cp LICENSE release/${{ matrix.target }}/
          tar -czf multios-${{ matrix.target }}.tar.gz -C release ${{ matrix.target }}

      - name: Generate checksums
        run: |
          cd release
          sha256sum multios-${{ matrix.target }}.tar.gz > multios-${{ matrix.target }}.tar.gz.sha256

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.target }}
          path: release/multios-${{ matrix.target }}*
          retention-days: 365

  # Build Docker images for each architecture
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        run: |
          docker run --rm --privileged multiarch/qemu-user-static \
            --reset -p yes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.target }}
          push: true
          tags: |
            multios/multios:${{ matrix.target }}
            multios/multios:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Create GitHub Release
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-release, build-docker]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release/

      - name: Organize artifacts
        run: |
          mkdir -p final-release
          find release/ -name "*.tar.gz" -exec cp {} final-release/ \;
          find release/ -name "*.sha256" -exec cp {} final-release/ \;
          ls -la final-release/

      - name: Generate changelog
        run: |
          ./scripts/generate_changelog.sh > CHANGELOG.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: final-release/*
          body_path: CHANGELOG.md
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}

      - name: Update latest tag
        if: "!contains(github.ref_name, '-')"
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/heads/main

  # Publish to package registries
  publish-registry:
    name: Publish to Registry
    runs-on: ubuntu-latest
    needs: [create-release]
    if: "!contains(github.ref_name, '-')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-install
        run: |
          cargo install cargo-install

      - name: Publish to crates.io
        run: |
          if [ "${{ secrets.CARGO_REGISTRY_TOKEN }}" ]; then
            cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
          fi

      - name: Publish to Docker Hub
        run: |
          docker pull multios/multios:${{ github.ref_name }}
          docker tag multios/multios:${{ github.ref_name }} multios/multios:latest
          docker push multios/multios:latest

  # Update documentation
  update-docs:
    name: Update Documentation
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate documentation
        run: |
          ./scripts/generate_docs.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/

  # Performance regression testing
  performance-regression:
    name: Performance Regression Test
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download previous release
        run: |
          ./scripts/download_previous_release.sh

      - name: Run performance comparison
        run: |
          ./scripts/compare_performance.sh

      - name: Upload performance report
        uses: actions/upload-artifact@v4
        with:
          name: performance-comparison
          path: reports/performance_comparison_*.json
          retention-days: 90

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('reports/performance_comparison_latest.json'));
            
            const comment = `## Performance Regression Report
            
            ### Key Metrics:
            - CPU Performance: ${report.cpu.performance_change}%
            - Memory Usage: ${report.memory.usage_change}%
            - Boot Time: ${report.boot.time_change}%
            
            ### Status: ${report.overall_status}
            
            ${report.significant_regressions ? '⚠️ Performance regressions detected!' : '✅ No significant regressions.'}
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });